### ISSUE TITLE
Error when running wb.run_wishbone

### ISSUE THREAD

**Issue by vlatkaa** [ManuSetty/wishbone#29] opened 2016-08-19 12:38 UTC
Hi,
I am getting an error when running a wb.run_wishbone function (on Ubuntu 14.04; the data size is 300 cells x 14000 genes). I tried running the function in both notebook and wishbone_gui.py and I am receiving the same error report, independent of the used parameters and whether choosing a starting cell or a gate. Please find the error report pasted below.

 Building lNN graph...
lNN computed in : 0.00 seconds
Determining waypoints if not specified...
Determining shortest path distances and perspectives....

/home/student/anaconda3/lib/python3.5/site-packages/wishbone/core.py:229: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  to_replace = np.random.randint(len(waypoints)-1, size=tailk)
/home/student/anaconda3/lib/python3.5/site-packages/wishbone/core.py:230: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  tailband_sample = np.random.choice( tailband, size=tailk, replace=False)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-9491e904efa9> in <module>()
----> 1 wb.run_wishbone(start_cell='c0h1_1', components_list=[1,2], num_waypoints=10)

/home/student/anaconda3/lib/python3.5/site-packages/wishbone/wb.py in run_wishbone(self, start_cell, branch, k, components_list, num_waypoints)
   1061         res = wishbone.core.wishbone(
   1062             self.scdata.diffusion_eigenvectors.ix[:, components_list].values,
-> 1063             s=s, k=k, l=k, num_waypoints=num_waypoints, branch=branch)
   1064 
   1065         # Assign results

/home/student/anaconda3/lib/python3.5/site-packages/wishbone/core.py in wishbone(data, s, k, l, num_graphs, num_waypoints, verbose, metric, voting_scheme, branch, flock_waypoints, band_sample, partial_order, search_connected_components)
     46 
     47                 #run traj. landmarks
---> 48                 traj, dist, iter_l, paths_l2l = _trajectory_landmarks( klnn, data, [s], num_waypoints, partial_order, verbose, metric, flock_waypoints, band_sample, branch)
     49                 if branch:
     50                         if verbose:

/home/student/anaconda3/lib/python3.5/site-packages/wishbone/core.py in _trajectory_landmarks(spdists, data, s, waypoints, partial_order, verbose, metric, flock_waypoints, band_sample, branch)
    259                 if i == 0:
    260                         dist = [list(temp[0].values())]
--> 261                         paths_l2l = [[paths[li] for li in l]]
    262                 else:
    263                         dist.append(list(temp[0].values()))

/home/student/anaconda3/lib/python3.5/site-packages/wishbone/core.py in <listcomp>(.0)
    259                 if i == 0:
    260                         dist = [list(temp[0].values())]
--> 261                         paths_l2l = [[paths[li] for li in l]]
    262                 else:
    263                         dist.append(list(temp[0].values()))

KeyError: 216

**Comment by ManuSetty** [comment] 2016-08-19 14:05
Hello

Can you try by increasing the k parameter for nearest neighbor construction ? This can be done using ```wb.run_wishbone(start_cell='c0h1_1', components_list=[1,2], num_waypoints=10, k=25)```. If this does not work, please email your counts matrix to ```manu.setty[@]columbia.edu``` and I will take a closer look since I am unable to reproduce this error using the sample data that is provided. 

Thanks

**Comment by vlatkaa** [comment] 2016-08-22 15:41
Thank you! I increased both num_waypoints and k parameter and now it works.

**Comment by ManuSetty** [comment] 2016-08-22 16:57
Great - I will close this Issue.

**Closed by ManuSetty** 2016-08-22 16:57 UTC
