### ISSUE TITLE
module 'wishbone' has no attribute 'wb'

### ISSUE THREAD

**Issue by marcRDM** [ManuSetty/wishbone#52] opened 2017-11-14 11:53 UTC
Hi there,

I just installed Wishbone and I have the exact same issue reported in issue #37.
Any new insight on what is happening and how to fix it..?

Thank you very much,
Marc

**Comment by ManuSetty** [comment] 2017-11-14 13:42
Hello

Can you please give me more details about how are trying to run Wishbone? Eg: Which operating system; are you trying to run this from command line or through notebook?

**Comment by marcRDM** [comment] 2017-11-14 14:02
I cloned it from github on a mac with python3 and I am trying to run it from jupyter notebook. I have the exact same thing as the screenshot in issue #37. I also tried from command line to import wb from wishbone, it does not recognise it.

**Comment by ManuSetty** [comment] 2017-11-14 15:24
Unfortunately, I am once again unable to reproduce this error. Can you tell me the directory from which you started the Jupyter notebook server? As before, probably the best approach would be do a fresh install of python3 and the dependencies. I would highly recommend using brew to install python.

**Comment by marcRDM** [comment] 2017-11-14 17:36
Thank you very much I did some reinstalling and it now works! Not sure why though...
I also had to install Cython manually. Cheers

**Comment by ManuSetty** [comment] 2017-11-14 19:44
Excellent! The Cython issue is fixed in the code and I will make a release shortly.

**Closed by ManuSetty** 2017-11-14 19:44 UTC
